@RestApi_HostAddress = http://localhost:5246

@lastPaymentId = ""

### Create a new payment

< {%

 

%}

POST {{RestApi_HostAddress}}/v1/payments
Content-Type: application/json

{
  "paymentMethod": "boleto",
  "paymentCode": "1234567890",
  "amount": 100,
  "currency": "BRL",
  "dueDate": "2024-08-31",
  "payer": {
    "name": "John Doe",
    "email": "johndoe@example.com",
    "cellPhoneNumber": "5541999887654",
    "document": {
      "type": "CPF",
      "number": "12345678909"
    },
    "address": {
      "street": "Rua dos Bobos",
      "number": "10",
      "complement": "Sala 1",
      "neighborhood": "Centro",
      "city": "São Paulo",
      "state": "SP",
      "country": "BR",
      "postalCode": "80100200"
    }
  },
  "postbackUrl": "{{RestApi_HostAddress}}/v1/echo?paymentId={{response.body.id}}"
}

> {%
    client.global.set("lastPaymentId", response.body.valueOf().id)
%}

### Get the last payment

< {%

    request.variables.set("lastPaymentId", client.global.get("lastPaymentId"))

%}

GET {{RestApi_HostAddress}}/v1/payments/{{lastPaymentId}}

> {%
    client.global.set("lastPaymentId", response.body.valueOf().id)
%}

### Confirm the last payment

< {%

    request.variables.set("lastPaymentId", client.global.get("lastPaymentId"))

%}

POST {{RestApi_HostAddress}}/v1/payments/{{lastPaymentId}}/confirm
Content-Type: application/json

{
  "paymentId": "{{lastPaymentId}}",
  "paidAmount": 100,
  "currency": "BRL",
  "paidOn": "2024-07-22"
}