@RestApi_HostAddress = http://localhost:5246

@lastPaymentId = ""

< {%
 
%}

POST {{RestApi_HostAddress}}/v1/payments
Content-Type: application/json

{
  "paymentMethod": "boleto",
  "paymentCode": "1234567890",
  "amount": 100,
  "currency": "BRL",
  "dueDate": "2024-08-31",
  "payer": {
    "name": "John Doe",
    "email": "johndoe@example.com",
    "cellPhoneNumber": "5541999887654",
    "document": {
      "type": "CPF",
      "number": "12345678909"
    },
    "address": {
      "street": "Rua dos Bobos",
      "number": "10",
      "complement": "Sala 1",
      "neighborhood": "Centro",
      "city": "São Paulo",
      "state": "SP",
      "country": "BR",
      "zipCode": "80100200"
    }
  },
  "postbackUrl": "http://localhost:3000/postback?key=1234567890"
}

> {%
    client.global.set("lastPaymentId", response.body.valueOf().id)
%}

###

< {%

    request.variables.set("lastPaymentId", client.global.get("lastPaymentId"))
 
 %}

GET {{RestApi_HostAddress}}/v1/payments/{{lastPaymentId}}
